# Generated by Django 4.1.9 on 2023-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("background_task", "0003_auto_20210905_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="heroku_dyno_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
