sudo: false
language: python

# this list can be easily checked by running `tox -l`
matrix:
  include:

    # the dist: xenial, sudo: true settings are currently needed to test with python 3.8
    - { python: "3.8", env: TOX_ENV=py38-django32-async, dist: xenial, sudo: true }
    - { python: "3.8", env: TOX_ENV=py38-django32-sync,  dist: xenial, sudo: true }
    - { python: "3.8", env: TOX_ENV=py38-django40-async, dist: xenial, sudo: true }
    - { python: "3.8", env: TOX_ENV=py38-django40-sync,  dist: xenial, sudo: true }

    # the dist: impish, sudo: true settings are currently needed to test with python 3.9
    - { python: "3.9", env: TOX_ENV=py39-django32-async, dist: xenial, sudo: true }
    - { python: "3.9", env: TOX_ENV=py39-django32-sync,  dist: xenial, sudo: true }
    - { python: "3.9", env: TOX_ENV=py39-django40-async, dist: xenial, sudo: true }
    - { python: "3.9", env: TOX_ENV=py39-django40-sync,  dist: xenial, sudo: true }

    # the dist: impish, sudo: true settings are currently needed to test with python 3.10
    - { python: "3.10", env: TOX_ENV=py310-django40-async, dist: impish, sudo: true }
    - { python: "3.10", env: TOX_ENV=py310-django40-sync,  dist: impish, sudo: true }

install: pip install tox-travis coveralls

script: tox -e $TOX_ENV

after_success: coveralls
